### ISSUE TITLE
Custom Characteristics not working. Error bluebird promise

### ISSUE THREAD

**Issue by leoneleone** [shauncampbell/homebridge-sky-plus-hd#11]
@shauncampbell 

I've run in to this error recently and not sure how to fix it. 
Any ideas? 

`    at tryCatcher (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)`

Thank you so much for the plugin by the way. It was extremely useful until it started getting this error.

**Comment by m11rphy** [comment]
I've just started get the same error

**Comment by leoneleone** [comment]
> Unhandled rejection Error: Failed to parse JSON string
>     at /usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_http-request.js:56:26
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:510:31)
>     at Promise._settlePromiseAt (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:584:18)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:700:14)
>     at Async._drainQueue (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:15:14)
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by leoneleone** [comment]
`Unhandled rejection Error: Failed to parse JSON string
    at /usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_http-request.js:56:26
    at tryCatcher (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)`

**Comment by bluntiless** [comment]
Just started seeing this also:
Turning channel to 411
Unhandled rejection Error: Channel not found
    at Object.ensureErrorObject (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:472:22)
    at Function.Promise.reject.Promise.rejected (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:199:9)
    at SkyPlusHDBox.setChannel (/usr/local/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_box.js:309:19)
    at SkyPlusHDBoxAccessory.setChannelNumber (/usr/local/lib/node_modules/homebridge-sky-plus-hd/index.js:96:10)
    at emitMany (events.js:147:13)
    at Characteristic.ChannelNumber.emit (events.js:224:7)
    at Characteristic.ChannelNumber.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:106:13)

**Comment by bluntiless** [comment]
I believe it is probably due to the new channel number reshuffle.

**Comment by leoneleone** [comment]
@bluntiless 
I don’t think you. It’s the Blubird dependency. I think the developer change the bluebird code quite drastically, and the code in this plugin no longer works.

@shauncampbell  If someone more knowledgable than me can try correct the Bluebird Promise error, please do 😬

**Comment by bluntiless** [comment]
@leoneleone
Do you think we can just downgrade the version of Bluebird to resolve this issue. If so, how to downgrade to an earlier version? Incidentally power on and off are still working correctly.

**Comment by leoneleone** [comment]
@bluntiless 
It’s either bluebird, or the Sky Remote dependency which uses bluebird as its dependency. 
I haven’t tried downgrading bluebird, but feel free to try it and report back. You’d have to look through Bluebird’s code update history, I’m sure the developer has made notes regarding the changes in his code. 

Either that, or the code for this plugin (homebridge-Sky-plus-hd) would have to modified. 
If you do manage to downgrade Bluebird, please let us know if that works.

**Comment by leoneleone** [comment]
@bluntiless 
Did you manage to downgrade bluebird and get it fixed?

**Comment by bluntiless** [comment]
Yes I downgraded bluebird but no joy, it made no difference! Just a shame but at least power on and off still works!

Sent from my iPhone

On 16 Aug 2018, at 15:03, leoneleone <notifications@github.com<mailto:notifications@github.com>> wrote:


@bluntiless<https://github.com/bluntiless>
Did you manage to downgrade bluebird and get it fixed?
