### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by stuartridout** [shauncampbell/homebridge-sky-plus-hd#7]
Hi,

I have installed in my homebridge when I'm receiving the following error.   Has anyone else experienced or resolved this?

thanks

----

Unhandled rejection Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: [
    at error (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sax/lib/sax.js:967:7)
    at Object.write (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sax/lib/sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/xml2js/lib/xml2js.js:540:19)
    at /usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_xml-parser.js:39:10
    at tryCatcher (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:71:37)
    at new SkyPlusHDXmlParser (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_xml-parser.js:38:9)
    at /usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/sky-plus-hd/lib/sky-plus-hd_event-listener.js:45:7
    at tryCatcher (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/homebridge-sky-plus-hd/node_modules/bluebird/js/main/promise.js:584:18)

**Comment by shauncampbell** [comment]
Hey,

This is a weird one, its not something I've seen before. Do you know what model of sky box you have? I wonder if its sending some xml that the app isn't expecting?
